services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $baseUrl: '%sendcloud.base_url%'
            string $apiKey: '%sendcloud.api_key%'
            string $apiSecret: '%sendcloud.api_secret%'

    Sendcloud\Bundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources,Tests}'

    Sendcloud\Bundle\Service\ShipmentService:
        bind:
            $logger: '@=container.has("monolog.logger." ~ parameter("sendcloud.logger_channel"))
                                    ? service("monolog.logger." ~ parameter("sendcloud.logger_channel"))
                                    : null'
